//! Byte-level BPE tokenizer (GPT-2 style, used by Qwen2.5 / Llama).
//!
//! Loads a HuggingFace `tokenizer.json` and implements encode/decode in pure
//! Rust: NFC normalization, the GPT-2 pre-tokenization regex, the byte-level
//! (byte -> unicode) mapping, and BPE merging by merge rank. Added/special
//! tokens (e.g. `<|im_start|>`) are matched literally before pre-tokenization.
//!
//! Numerically validated against `tokenizers` 0.23.1 (HF) via
//! `crates/mach-model/tests/data/tok_golden.json` (generated by
//! `tools/_gen_golden.py` in the `.venv-tok` virtualenv).

use fancy_regex::Regex;
use std::collections::HashMap;
use unicode_normalization::UnicodeNormalization;

/// The GPT-2 pre-tokenization regex (standard for Qwen2.5 / Llama BPE).
const PRE_TOKENIZE_RE: &str = r#"(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^
\p{L}\p{N}]?\p{L}+|\p{N}| ?[^\s\p{L}\p{N}]+[
]*|\s*[
]+|\s+(?!\S)|\s+"#;

/// Byte <-> unicode maps (GPT-2 `bytes_to_unicode`).
struct ByteMap {
    to_char: [char; 256],
    /// char code -> byte, or -1 when the char is not a byte-level char.
    to_byte: [i32; 512],
}

impl ByteMap {
    fn new() -> Self {
        let mut to_char = ['\0'; 256];
        let mut bs: Vec<u8> = (33..=126).chain(161..=172).chain(174..=255).collect();
        let mut cs: Vec<u32> = bs.iter().map(|&b| u32::from(b)).collect();
        let mut n = 0u32;
        for b in 0u32..=255 {
            if !bs.contains(&(b as u8)) {
                bs.push(b as u8);
                cs.push(256 + n);
                n += 1;
            }
        }
        for (&b, &c) in bs.iter().zip(cs.iter()) {
            to_char[b as usize] = char::from_u32(c).expect("valid byte char");
        }
        let mut to_byte = [-1i32; 512];
        for (&b, &c) in bs.iter().zip(cs.iter()) {
            to_byte[c as usize] = i32::from(b);
        }
        Self { to_char, to_byte }
    }
}

/// A loaded byte-level BPE tokenizer.
pub struct Tokenizer {
    vocab: HashMap<String, u32>,
    id_to_token: Vec<String>,
    bpe_ranks: HashMap<(String, String), u32>,
    /// Added (special) tokens: (content, id), longest content first.
    added: Vec<(String, u32)>,
    byte_map: ByteMap,
    pre_regex: Regex,
}

impl Tokenizer {
    /// Loads a HuggingFace `tokenizer.json`.
    pub fn from_path(path: &std::path::Path) -> Result<Self, crate::Error> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| crate::Error::Model(format!("read tokenizer: {e}")))?;
        Self::from_json(&text)
    }

    /// Parses a HuggingFace `tokenizer.json` document.
    pub fn from_json(text: &str) -> Result<Self, crate::Error> {
        let v: serde_json::Value = serde_json::from_str(text)
            .map_err(|e| crate::Error::Model(format!("parse tokenizer.json: {e}")))?;
        let model = v
            .get("model")
            .ok_or_else(|| crate::Error::Model("tokenizer.json: missing model".into()))?;
        let vocab_obj = model
            .get("vocab")
            .ok_or_else(|| crate::Error::Model("tokenizer.json: missing vocab".into()))?;
        let mut vocab: HashMap<String, u32> = HashMap::with_capacity(160_000);
        if let Some(obj) = vocab_obj.as_object() {
            for (k, val) in obj {
                if let Some(id) = val.as_u64() {
                    vocab.insert(k.clone(), id as u32);
                }
            }
        }
        let mut id_to_token: Vec<String> = vec![String::new(); vocab.len()];
        for (k, &id) in &vocab {
            if let Some(slot) = id_to_token.get_mut(id as usize) {
                *slot = k.clone();
            }
        }
        let mut bpe_ranks: HashMap<(String, String), u32> = HashMap::new();
        if let Some(merges) = model.get("merges").and_then(|m| m.as_array()) {
            for (rank, m) in merges.iter().enumerate() {
                // HF serializes each merge as a single "left right" string
                // (byte-level tokens never contain spaces, so the separator is
                // unambiguous); older dumps use ["left", "right"] arrays.
                let pair: Option<(String, String)> = if let Some(s) = m.as_str() {
                    s.rfind(' ')
                        .map(|i| (s[..i].to_string(), s[i + 1..].to_string()))
                } else if let Some(arr) = m.as_array() {
                    if arr.len() == 2 {
                        match (arr[0].as_str(), arr[1].as_str()) {
                            (Some(a), Some(b)) => Some((a.to_string(), b.to_string())),
                            _ => None,
                        }
                    } else {
                        None
                    }
                } else {
                    None
                };
                if let Some((a, b)) = pair {
                    bpe_ranks.insert((a, b), rank as u32);
                }
            }
        }
        // Added (special) tokens, longest content first for matching.
        let mut added: Vec<(String, u32)> = Vec::new();
        if let Some(list) = v.get("added_tokens").and_then(|a| a.as_array()) {
            for t in list {
                if let (Some(content), Some(id)) = (
                    t.get("content").and_then(|c| c.as_str()),
                    t.get("id").and_then(|i| i.as_u64()),
                ) {
                    added.push((content.to_string(), id as u32));
                }
            }
        }
        added.sort_by_key(|a| std::cmp::Reverse(a.0.len()));
        let pre_regex = Regex::new(PRE_TOKENIZE_RE)
            .map_err(|e| crate::Error::Model(format!("pre-tokenize regex: {e}")))?;
        Ok(Self {
            vocab,
            id_to_token,
            bpe_ranks,
            added,
            byte_map: ByteMap::new(),
            pre_regex,
        })
    }

    /// Vocabulary size.
    #[must_use]
    pub fn vocab_size(&self) -> usize {
        self.vocab.len() + self.added.len()
    }

    /// Encodes `text` to token ids (added tokens matched literally first).
    #[must_use]
    pub fn encode(&self, text: &str) -> Vec<u32> {
        let normalized: String = text.nfc().collect();
        let mut out = Vec::new();
        self.encode_specials(&normalized, &mut out);
        out
    }

    /// Raw byte stream for `ids` (before UTF-8 reassembly); used for
    /// incremental streaming decode so multi-byte characters survive token
    /// boundaries.
    #[must_use]
    pub fn decode_bytes(&self, ids: &[u32]) -> Vec<u8> {
        let mut bytes = Vec::with_capacity(ids.len() * 4);
        for &id in ids {
            if let Some(tok) = self.id_to_token.get(id as usize) {
                for c in tok.chars() {
                    let code = c as u32;
                    if (code as usize) < self.byte_map.to_byte.len() {
                        let b = self.byte_map.to_byte[code as usize];
                        if b >= 0 {
                            bytes.push(b as u8);
                            continue;
                        }
                    }
                    let mut buf = [0u8; 4];
                    bytes.extend_from_slice(c.encode_utf8(&mut buf).as_bytes());
                }
            }
        }
        bytes
    }

    /// Decodes token ids back to text (byte-level reverse mapping).
    #[must_use]
    pub fn decode(&self, ids: &[u32]) -> String {
        // ByteLevel decode is lossy, like HF (invalid sequences -> U+FFFD).
        String::from_utf8_lossy(&self.decode_bytes(ids)).into_owned()
    }

    fn encode_specials(&self, text: &str, out: &mut Vec<u32>) {
        let chars: Vec<char> = text.chars().collect();
        let mut i = 0usize;
        let mut buf = String::new();
        while i < chars.len() {
            let mut matched: Option<&(String, u32)> = None;
            for a in &self.added {
                let ac: Vec<char> = a.0.chars().collect();
                if !ac.is_empty()
                    && chars[i..].starts_with(&ac)
                    && matched.is_none_or(|m| a.0.len() > m.0.len())
                {
                    matched = Some(a);
                }
            }
            if let Some(a) = matched {
                if !buf.is_empty() {
                    self.encode_plain(&buf, out);
                    buf.clear();
                }
                out.push(a.1);
                i += a.0.chars().count();
            } else {
                buf.push(chars[i]);
                i += 1;
            }
        }
        if !buf.is_empty() {
            self.encode_plain(&buf, out);
        }
    }

    fn encode_plain(&self, text: &str, out: &mut Vec<u32>) {
        for m in self
            .pre_regex
            .find_iter(text)
            .map(|r| r.expect("regex match"))
        {
            let word = &text[m.start()..m.end()];
            let chars: Vec<char> = word
                .bytes()
                .map(|b| self.byte_map.to_char[b as usize])
                .collect();
            for unit in self.bpe(&chars) {
                let id = self.vocab[&unit];
                out.push(id);
            }
        }
    }

    /// Greedy BPE merge: repeatedly merge the lowest-rank adjacent pair.
    fn bpe(&self, chars: &[char]) -> Vec<String> {
        if chars.is_empty() {
            return Vec::new();
        }
        let mut parts: Vec<String> = chars.iter().map(|c| c.to_string()).collect();
        loop {
            let mut best: Option<(u32, usize)> = None;
            for i in 0..parts.len() - 1 {
                if let Some(&r) = self
                    .bpe_ranks
                    .get(&(parts[i].clone(), parts[i + 1].clone()))
                    && best.is_none_or(|(br, _)| r < br)
                {
                    best = Some((r, i));
                }
            }
            let Some((_, i)) = best else { break };
            let merged = format!("{}{}", parts[i], parts[i + 1]);
            parts[i] = merged;
            parts.remove(i + 1);
        }
        parts
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn golden_path() -> Option<PathBuf> {
        [
            PathBuf::from("tests/data/tok_golden.json"),
            PathBuf::from("../../tests/data/tok_golden.json"),
        ]
        .into_iter()
        .find(|p| p.exists())
    }

    fn tokenizer_path() -> Option<PathBuf> {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        [
            root.join("..")
                .join("..")
                .join(".models")
                .join("tokenizer.json"),
            root.join(".models").join("tokenizer.json"),
        ]
        .into_iter()
        .find(|p| p.exists())
    }

    fn load() -> Option<Tokenizer> {
        let p = tokenizer_path()?;
        Tokenizer::from_path(&p).ok()
    }

    #[test]
    fn golden_encode_matches_hf() {
        let Some(gp) = golden_path() else {
            eprintln!("skipping: tok_golden.json missing");
            return;
        };
        let Some(tj) = tokenizer_path() else {
            eprintln!("skipping: tokenizer.json missing");
            return;
        };
        let tok = Tokenizer::from_path(&tj).expect("load tokenizer");
        let golden: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(gp).expect("read golden"))
                .expect("parse golden");
        let enc = &golden["enc"];
        for (key, case) in enc.as_object().expect("enc object") {
            let text = case["text"].as_str().expect("text");
            let want: Vec<u32> = case["ids"]
                .as_array()
                .expect("ids")
                .iter()
                .map(|v| v.as_u64().unwrap() as u32)
                .collect();
            let got = tok.encode(text);
            assert_eq!(got, want, "encode mismatch for case {key}: {text:?}",);
        }
        // decode cases
        for case in golden["dec"].as_array().expect("dec array") {
            let ids: Vec<u32> = case["ids"]
                .as_array()
                .expect("ids")
                .iter()
                .map(|v| v.as_u64().unwrap() as u32)
                .collect();
            let want = case["text"].as_str().expect("text");
            let got = tok.decode(&ids);
            assert_eq!(&got, want, "decode mismatch for ids {ids:?}");
        }
        // special token handling
        let extra = &golden["extra"];
        let text = "hi <|im_start|> there";
        let want: Vec<u32> = extra["encode_with_special"]
            .as_array()
            .expect("ids")
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        assert_eq!(tok.encode(text), want, "special-token encode mismatch");
    }

    #[test]
    fn round_trip_preserves_text() {
        let Some(tok) = load() else {
            eprintln!("skipping: tokenizer.json/golden missing");
            return;
        };
        for s in [
            "Hello, world!",
            "你好，世界！MachServe 推理引擎",
            "café naïve",
            "Emoji 😀🚀",
            "mixed 123 case 4.56",
            "  spaces  and	tabs ",
        ] {
            let ids = tok.encode(s);
            let back = tok.decode(&ids);
            assert_eq!(back, s, "round-trip failed for {s:?}");
        }
    }
}
