//! Byte-level BPE tokenizer (GPT-2 style, used by Qwen2.5 / Llama).
//!
//! Loads a HuggingFace `tokenizer.json` and implements encode/decode in pure
//! Rust: NFC normalization, the GPT-2 pre-tokenization regex, the byte-level
//! (byte -> unicode) mapping, and BPE merging by merge rank. Added/special
//! tokens (e.g. `<|im_start|>`) are matched literally before pre-tokenization.
//!
//! Numerically validated against `tokenizers` 0.23.1 (HF) via
//! `crates/mach-model/tests/data/tok_golden.json` (generated by
//! `tools/_gen_golden.py` in the `.venv-tok` virtualenv).

use fancy_regex::Regex;
use std::collections::HashMap;
use unicode_normalization::UnicodeNormalization;

/// One pre-tokenizer step from a HuggingFace `tokenizer.json`.
///
/// Real checkpoints do not agree on pre-tokenization: Qwen2.5/Llama ship a
/// single `Split` with the GPT-2 regex, while DeepSeek-V2 ships a chain of
/// five `Split`s (newlines, letter runs, punctuation runs, trailing spaces,
/// CJK runs) plus a `Digits` step that emits every digit separately. A
/// hardcoded GPT-2 regex silently mis-tokenizes the latter (digits and CJK
/// boundaries come out wrong), so the chain is read from the checkpoint.
enum PreStep {
    /// `Split` with a regex: matches are kept as their own pieces, and the
    /// text between them is kept too (HF `Isolated` behavior).
    Regex(Regex),
    /// `Digits`: separates digit runs from the rest; `true` emits every digit
    /// as its own piece (`individual_digits`).
    Digits(bool),
}

/// The GPT-2 pre-tokenization regex (standard for Qwen2.5 / Llama BPE).
///
/// Used only as a fallback when `tokenizer.json` carries no `pre_tokenizer`.
const PRE_TOKENIZE_RE: &str = r#"(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^
\p{L}\p{N}]?\p{L}+|\p{N}| ?[^\s\p{L}\p{N}]+[
]*|\s*[
]+|\s+(?!\S)|\s+"#;

/// Byte <-> unicode maps (GPT-2 `bytes_to_unicode`).
struct ByteMap {
    to_char: [char; 256],
    /// char code -> byte, or -1 when the char is not a byte-level char.
    to_byte: [i32; 512],
}

impl ByteMap {
    fn new() -> Self {
        let mut to_char = ['\0'; 256];
        let mut bs: Vec<u8> = (33..=126).chain(161..=172).chain(174..=255).collect();
        let mut cs: Vec<u32> = bs.iter().map(|&b| u32::from(b)).collect();
        let mut n = 0u32;
        for b in 0u32..=255 {
            if !bs.contains(&(b as u8)) {
                bs.push(b as u8);
                cs.push(256 + n);
                n += 1;
            }
        }
        for (&b, &c) in bs.iter().zip(cs.iter()) {
            to_char[b as usize] = char::from_u32(c).expect("valid byte char");
        }
        let mut to_byte = [-1i32; 512];
        for (&b, &c) in bs.iter().zip(cs.iter()) {
            to_byte[c as usize] = i32::from(b);
        }
        Self { to_char, to_byte }
    }
}

/// True when the tokenizer declares NFC normalization anywhere in its
/// `normalizer` (a bare `NFC` or a `Sequence` containing one).
///
/// Qwen2.5/Llama declare `{"type":"NFC"}`; DeepSeek-V2 declares an empty
/// `Sequence`, i.e. NO normalization — normalizing anyway would diverge from
/// HuggingFace on text whose bytes are not already in NFC form.
fn normalizer_is_nfc(v: Option<&serde_json::Value>) -> bool {
    let Some(v) = v else {
        return false;
    };
    match v.get("type").and_then(|t| t.as_str()) {
        Some("NFC") => true,
        Some("Sequence") => v
            .get("normalizers")
            .and_then(|n| n.as_array())
            .is_some_and(|a| {
                a.iter()
                    .any(|n| n.get("type").and_then(|t| t.as_str()) == Some("NFC"))
            }),
        _ => false,
    }
}

/// Parses a HuggingFace `pre_tokenizer` into a [`PreStep`] chain.
///
/// Steps we do not need to model are skipped (`ByteLevel` — this tokenizer
/// always maps bytes itself). A missing or unparseable chain yields an empty
/// `Vec`, which makes the caller fall back to the GPT-2 regex.
fn parse_pre_tokenizer(v: Option<&serde_json::Value>) -> Vec<PreStep> {
    let mut steps = Vec::new();
    let Some(v) = v else {
        return steps;
    };
    let list: Vec<&serde_json::Value> = match v.get("type").and_then(|t| t.as_str()) {
        Some("Sequence") => v
            .get("pretokenizers")
            .and_then(|p| p.as_array())
            .map(|a| a.iter().collect())
            .unwrap_or_default(),
        _ => vec![v],
    };
    for step in list {
        match step.get("type").and_then(|t| t.as_str()) {
            Some("Split") => {
                let Some(pat) = step
                    .get("pattern")
                    .and_then(|p| p.get("Regex"))
                    .and_then(|r| r.as_str())
                else {
                    continue;
                };
                match Regex::new(pat) {
                    Ok(re) => steps.push(PreStep::Regex(re)),
                    Err(e) => eprintln!("tokenizer: unsupported pre-tokenizer regex: {e}"),
                }
            }
            // `Digits`: `individual_digits` (default true) emits one piece per
            // digit; DeepSeek-V2 relies on it (digits never merge across).
            Some("Digits") => steps.push(PreStep::Digits(
                step.get("individual_digits")
                    .and_then(|b| b.as_bool())
                    .unwrap_or(true),
            )),
            _ => {}
        }
    }
    steps
}

/// Splits `s` into digit / non-digit pieces (`Digits` pre-tokenizer): with
/// `individual`, every digit becomes its own piece.
fn push_digit_pieces<'a>(s: &'a str, individual: bool, out: &mut Vec<&'a str>) {
    if s.is_empty() {
        return;
    }
    let bytes = s.as_bytes();
    let mut i = 0usize;
    while i < bytes.len() {
        let is_digit = bytes[i].is_ascii_digit();
        let mut j = i;
        while j < bytes.len() && bytes[j].is_ascii_digit() == is_digit {
            j += 1;
        }
        let chunk = &s[i..j];
        if is_digit && individual {
            // Byte-safe: ASCII digits are single bytes, so slicing on byte
            // offsets cannot split a multi-byte character.
            for k in 0..chunk.len() {
                out.push(&chunk[k..k + 1]);
            }
        } else {
            out.push(chunk);
        }
        i = j;
    }
}

/// A loaded byte-level BPE tokenizer.
pub struct Tokenizer {
    vocab: HashMap<String, u32>,
    id_to_token: Vec<String>,
    bpe_ranks: HashMap<(String, String), u32>,
    /// Added (special) tokens: (content, id), longest content first.
    added: Vec<(String, u32)>,
    byte_map: ByteMap,
    /// Pre-tokenizer chain read from `tokenizer.json` (see [`PreStep`]).
    pre_steps: Vec<PreStep>,
    /// Whether the checkpoint declares NFC normalization (Qwen: yes;
    /// DeepSeek-V2: no — its `normalizer` is an empty `Sequence`).
    nfc: bool,
    /// Fallback regex when the json carries no `pre_tokenizer`.
    pre_regex: Regex,
}

impl Tokenizer {
    /// Loads a HuggingFace `tokenizer.json`.
    pub fn from_path(path: &std::path::Path) -> Result<Self, crate::Error> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| crate::Error::Model(format!("read tokenizer: {e}")))?;
        Self::from_json(&text)
    }

    /// Parses a HuggingFace `tokenizer.json` document.
    pub fn from_json(text: &str) -> Result<Self, crate::Error> {
        let v: serde_json::Value = serde_json::from_str(text)
            .map_err(|e| crate::Error::Model(format!("parse tokenizer.json: {e}")))?;
        let model = v
            .get("model")
            .ok_or_else(|| crate::Error::Model("tokenizer.json: missing model".into()))?;
        let vocab_obj = model
            .get("vocab")
            .ok_or_else(|| crate::Error::Model("tokenizer.json: missing vocab".into()))?;
        let mut vocab: HashMap<String, u32> = HashMap::with_capacity(160_000);
        if let Some(obj) = vocab_obj.as_object() {
            for (k, val) in obj {
                if let Some(id) = val.as_u64() {
                    vocab.insert(k.clone(), id as u32);
                }
            }
        }
        let mut id_to_token: Vec<String> = vec![String::new(); vocab.len()];
        for (k, &id) in &vocab {
            if let Some(slot) = id_to_token.get_mut(id as usize) {
                *slot = k.clone();
            }
        }
        let mut bpe_ranks: HashMap<(String, String), u32> = HashMap::new();
        if let Some(merges) = model.get("merges").and_then(|m| m.as_array()) {
            for (rank, m) in merges.iter().enumerate() {
                // HF serializes each merge as a single "left right" string
                // (byte-level tokens never contain spaces, so the separator is
                // unambiguous); older dumps use ["left", "right"] arrays.
                let pair: Option<(String, String)> = if let Some(s) = m.as_str() {
                    s.rfind(' ')
                        .map(|i| (s[..i].to_string(), s[i + 1..].to_string()))
                } else if let Some(arr) = m.as_array() {
                    if arr.len() == 2 {
                        match (arr[0].as_str(), arr[1].as_str()) {
                            (Some(a), Some(b)) => Some((a.to_string(), b.to_string())),
                            _ => None,
                        }
                    } else {
                        None
                    }
                } else {
                    None
                };
                if let Some((a, b)) = pair {
                    bpe_ranks.insert((a, b), rank as u32);
                }
            }
        }
        // Added (special) tokens, longest content first for matching.
        let mut added: Vec<(String, u32)> = Vec::new();
        if let Some(list) = v.get("added_tokens").and_then(|a| a.as_array()) {
            for t in list {
                if let (Some(content), Some(id)) = (
                    t.get("content").and_then(|c| c.as_str()),
                    t.get("id").and_then(|i| i.as_u64()),
                ) {
                    added.push((content.to_string(), id as u32));
                }
            }
        }
        added.sort_by_key(|a| std::cmp::Reverse(a.0.len()));
        // Pre-tokenizer chain + normalizer come from the checkpoint: Qwen and
        // DeepSeek disagree on both, and a hardcoded GPT-2 regex silently
        // mis-tokenizes DeepSeek (digit runs and CJK boundaries differ).
        let pre_steps = parse_pre_tokenizer(v.get("pre_tokenizer"));
        let nfc = normalizer_is_nfc(v.get("normalizer"));
        let pre_regex = Regex::new(PRE_TOKENIZE_RE)
            .map_err(|e| crate::Error::Model(format!("pre-tokenize regex: {e}")))?;
        Ok(Self {
            vocab,
            id_to_token,
            bpe_ranks,
            added,
            byte_map: ByteMap::new(),
            pre_steps,
            nfc,
            pre_regex,
        })
    }

    /// Splits `text` into BPE pieces: the pre-tokenizer chain when the
    /// checkpoint declares one, else the GPT-2 regex.
    fn pre_pieces<'a>(&self, text: &'a str) -> Vec<&'a str> {
        if self.pre_steps.is_empty() {
            return self
                .pre_regex
                .find_iter(text)
                .map(|r| r.expect("regex match"))
                .map(|m| &text[m.start()..m.end()])
                .collect();
        }
        let mut pieces: Vec<&str> = vec![text];
        for step in &self.pre_steps {
            let mut next: Vec<&str> = Vec::with_capacity(pieces.len());
            for p in pieces {
                match step {
                    PreStep::Regex(re) => {
                        let mut last = 0usize;
                        for m in re.find_iter(p).map(|r| r.expect("regex match")) {
                            // `Isolated`: the gap before a match and the match
                            // itself are both pieces.
                            if m.start() > last {
                                next.push(&p[last..m.start()]);
                            }
                            next.push(&p[m.start()..m.end()]);
                            last = m.end();
                        }
                        if last < p.len() {
                            next.push(&p[last..]);
                        }
                    }
                    PreStep::Digits(individual) => push_digit_pieces(p, *individual, &mut next),
                }
            }
            pieces = next;
        }
        pieces.retain(|p| !p.is_empty());
        pieces
    }

    /// Vocabulary size.
    #[must_use]
    pub fn vocab_size(&self) -> usize {
        self.vocab.len() + self.added.len()
    }

    /// Token id for an added/special token by exact content (e.g.
    /// `<|im_end|>`), or `None` when it is not an added token.
    #[must_use]
    pub fn special_token_id(&self, content: &str) -> Option<u32> {
        self.added
            .iter()
            .find(|(c, _)| c == content)
            .map(|(_, id)| *id)
    }

    /// Encodes `text` to token ids (added tokens matched literally first).
    #[must_use]
    pub fn encode(&self, text: &str) -> Vec<u32> {
        // NFC only when the checkpoint declares it (Qwen does; DeepSeek-V2
        // does not — its `normalizer` is an empty `Sequence`).
        let normalized: String = if self.nfc {
            text.nfc().collect()
        } else {
            text.to_string()
        };
        let mut out = Vec::new();
        self.encode_specials(&normalized, &mut out);
        out
    }

    /// Raw byte stream for `ids` (before UTF-8 reassembly); used for
    /// incremental streaming decode so multi-byte characters survive token
    /// boundaries.
    #[must_use]
    pub fn decode_bytes(&self, ids: &[u32]) -> Vec<u8> {
        let mut bytes = Vec::with_capacity(ids.len() * 4);
        for &id in ids {
            if let Some(tok) = self.id_to_token.get(id as usize) {
                for c in tok.chars() {
                    let code = c as u32;
                    if (code as usize) < self.byte_map.to_byte.len() {
                        let b = self.byte_map.to_byte[code as usize];
                        if b >= 0 {
                            bytes.push(b as u8);
                            continue;
                        }
                    }
                    let mut buf = [0u8; 4];
                    bytes.extend_from_slice(c.encode_utf8(&mut buf).as_bytes());
                }
            }
        }
        bytes
    }

    /// Decodes token ids back to text (byte-level reverse mapping).
    #[must_use]
    pub fn decode(&self, ids: &[u32]) -> String {
        // ByteLevel decode is lossy, like HF (invalid sequences -> U+FFFD).
        String::from_utf8_lossy(&self.decode_bytes(ids)).into_owned()
    }

    fn encode_specials(&self, text: &str, out: &mut Vec<u32>) {
        let chars: Vec<char> = text.chars().collect();
        let mut i = 0usize;
        let mut buf = String::new();
        while i < chars.len() {
            let mut matched: Option<&(String, u32)> = None;
            for a in &self.added {
                let ac: Vec<char> = a.0.chars().collect();
                if !ac.is_empty()
                    && chars[i..].starts_with(&ac)
                    && matched.is_none_or(|m| a.0.len() > m.0.len())
                {
                    matched = Some(a);
                }
            }
            if let Some(a) = matched {
                if !buf.is_empty() {
                    self.encode_plain(&buf, out);
                    buf.clear();
                }
                out.push(a.1);
                i += a.0.chars().count();
            } else {
                buf.push(chars[i]);
                i += 1;
            }
        }
        if !buf.is_empty() {
            self.encode_plain(&buf, out);
        }
    }

    fn encode_plain(&self, text: &str, out: &mut Vec<u32>) {
        for word in self.pre_pieces(text) {
            let chars: Vec<char> = word
                .bytes()
                .map(|b| self.byte_map.to_char[b as usize])
                .collect();
            for unit in self.bpe(&chars) {
                let id = self.vocab[&unit];
                out.push(id);
            }
        }
    }

    /// Greedy BPE merge: repeatedly merge the lowest-rank adjacent pair.
    fn bpe(&self, chars: &[char]) -> Vec<String> {
        if chars.is_empty() {
            return Vec::new();
        }
        let mut parts: Vec<String> = chars.iter().map(|c| c.to_string()).collect();
        loop {
            let mut best: Option<(u32, usize)> = None;
            for i in 0..parts.len() - 1 {
                if let Some(&r) = self
                    .bpe_ranks
                    .get(&(parts[i].clone(), parts[i + 1].clone()))
                    && best.is_none_or(|(br, _)| r < br)
                {
                    best = Some((r, i));
                }
            }
            let Some((_, i)) = best else { break };
            let merged = format!("{}{}", parts[i], parts[i + 1]);
            parts[i] = merged;
            parts.remove(i + 1);
        }
        parts
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn golden_path() -> Option<PathBuf> {
        [
            PathBuf::from("tests/data/tok_golden.json"),
            PathBuf::from("../../tests/data/tok_golden.json"),
        ]
        .into_iter()
        .find(|p| p.exists())
    }

    fn tokenizer_path() -> Option<PathBuf> {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        [
            root.join("..")
                .join("..")
                .join(".models")
                .join("tokenizer.json"),
            root.join(".models").join("tokenizer.json"),
        ]
        .into_iter()
        .find(|p| p.exists())
    }

    fn load() -> Option<Tokenizer> {
        let p = tokenizer_path()?;
        Tokenizer::from_path(&p).ok()
    }

    #[test]
    fn golden_encode_matches_hf() {
        let Some(gp) = golden_path() else {
            eprintln!("skipping: tok_golden.json missing");
            return;
        };
        let Some(tj) = tokenizer_path() else {
            eprintln!("skipping: tokenizer.json missing");
            return;
        };
        let tok = Tokenizer::from_path(&tj).expect("load tokenizer");
        let golden: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(gp).expect("read golden"))
                .expect("parse golden");
        let enc = &golden["enc"];
        for (key, case) in enc.as_object().expect("enc object") {
            let text = case["text"].as_str().expect("text");
            let want: Vec<u32> = case["ids"]
                .as_array()
                .expect("ids")
                .iter()
                .map(|v| v.as_u64().unwrap() as u32)
                .collect();
            let got = tok.encode(text);
            assert_eq!(got, want, "encode mismatch for case {key}: {text:?}",);
        }
        // decode cases
        for case in golden["dec"].as_array().expect("dec array") {
            let ids: Vec<u32> = case["ids"]
                .as_array()
                .expect("ids")
                .iter()
                .map(|v| v.as_u64().unwrap() as u32)
                .collect();
            let want = case["text"].as_str().expect("text");
            let got = tok.decode(&ids);
            assert_eq!(&got, want, "decode mismatch for ids {ids:?}");
        }
        // special token handling
        let extra = &golden["extra"];
        let text = "hi <|im_start|> there";
        let want: Vec<u32> = extra["encode_with_special"]
            .as_array()
            .expect("ids")
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        assert_eq!(tok.encode(text), want, "special-token encode mismatch");
    }

    /// DeepSeek-V2-Lite (`tokenizer_config` differs from Qwen's in the three
    /// ways that change token ids: no NFC normalizer, a two-step `Split`
    /// pre-tokenizer chain, and a ByteLevel decoder with
    /// `add_prefix_space: true`). Opt-in: `.models/` is gitignored, so the
    /// test skips when the checkpoint is absent.
    fn deepseek_golden_path() -> Option<PathBuf> {
        [
            PathBuf::from("tests/data/tok_golden_deepseek.json"),
            PathBuf::from("../../tests/data/tok_golden_deepseek.json"),
        ]
        .into_iter()
        .find(|p| p.exists())
    }

    fn deepseek_tokenizer_path() -> Option<PathBuf> {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        [
            root.join("..")
                .join("..")
                .join(".models")
                .join("deepseek-v2-lite-chat")
                .join("tokenizer.json"),
            root.join(".models")
                .join("deepseek-v2-lite-chat")
                .join("tokenizer.json"),
        ]
        .into_iter()
        .find(|p| p.exists())
    }

    #[test]
    fn deepseek_golden_encode_matches_hf() {
        let Some(gp) = deepseek_golden_path() else {
            eprintln!("skipping: tok_golden_deepseek.json missing");
            return;
        };
        let Some(tj) = deepseek_tokenizer_path() else {
            eprintln!("skipping: DeepSeek-V2-Lite tokenizer.json missing");
            return;
        };
        let tok = Tokenizer::from_path(&tj).expect("load DeepSeek tokenizer");
        let golden: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(gp).expect("read golden"))
                .expect("parse golden");
        for (key, case) in golden["enc"].as_object().expect("enc object") {
            let text = case["text"].as_str().expect("text");
            let want: Vec<u32> = case["ids"]
                .as_array()
                .expect("ids")
                .iter()
                .map(|v| v.as_u64().unwrap() as u32)
                .collect();
            let got = tok.encode(text);
            assert_eq!(got, want, "DeepSeek encode mismatch {key}: {text:?}");
        }
        for case in golden["dec"].as_array().expect("dec array") {
            let ids: Vec<u32> = case["ids"]
                .as_array()
                .expect("ids")
                .iter()
                .map(|v| v.as_u64().unwrap() as u32)
                .collect();
            let want = case["text"].as_str().expect("text");
            let got = tok.decode(&ids);
            assert_eq!(&got, want, "DeepSeek decode mismatch for ids {ids:?}");
        }
        // `add_special_tokens` is not modelled by `encode`, so both HF rows
        // must agree with it — the server's chat template emits BOS itself.
        let extra = &golden["extra"];
        let want: Vec<u32> = extra["encode_with_special"]
            .as_array()
            .expect("ids")
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        assert_eq!(tok.encode("hi"), want, "DeepSeek 'hi' encode mismatch");
        let want_no: Vec<u32> = extra["encode_without_special"]
            .as_array()
            .expect("ids")
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        assert_eq!(
            want, want_no,
            "DeepSeek tokenizer.json must not add BOS in `encode` \
             (the chat template does)"
        );
        // The server stops generation on this id; a wrong special id would
        // decode past the end of the answer forever. Delimiters are U+FF5C
        // (fullwidth vertical line) and U+2581 — not ASCII `|`.
        let eos: u32 = extra["eos_id"].as_u64().unwrap() as u32;
        let eos_text = "<\u{ff5c}end\u{2581}of\u{2581}sentence\u{ff5c}>";
        assert_eq!(tok.special_token_id(eos_text), Some(eos), "eos id");
        let bos: u32 = extra["bos_id"].as_u64().unwrap() as u32;
        let bos_text = "<\u{ff5c}begin\u{2581}of\u{2581}sentence\u{ff5c}>";
        assert_eq!(tok.special_token_id(bos_text), Some(bos), "bos id");
    }

    #[test]
    fn round_trip_preserves_text() {
        let Some(tok) = load() else {
            eprintln!("skipping: tokenizer.json/golden missing");
            return;
        };
        for s in [
            "Hello, world!",
            "你好，世界！MachServe 推理引擎",
            "café naïve",
            "Emoji 😀🚀",
            "mixed 123 case 4.56",
            "  spaces  and	tabs ",
        ] {
            let ids = tok.encode(s);
            let back = tok.decode(&ids);
            assert_eq!(back, s, "round-trip failed for {s:?}");
        }
    }
}
